services:
  - type: web
    name: finance-api
    runtime: node
    rootDir: finance-api
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://finance-data-processing-and-access-one.vercel.app,https://finance-data-processing-and-access-amber.vercel.app,https://finance-data-processing-and-access-six.vercel.app
